---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: freshrss
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: freshrss-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        POSTGRES_USER: &db_user "{{ .POSTGRES_USER }}"
        POSTGRES_PASSWORD: &db_pass "{{ .POSTGRES_PASS }}"
        POSTGRES_DB: &db_name freshrss
        POSTGRES_HOST: &db_host postgres16-rw.database.svc.cluster.local
        # Postgres Init
        INIT_POSTGRES_DBNAME: *db_name
        INIT_POSTGRES_HOST: *db_host
        INIT_POSTGRES_USER: *db_user
        INIT_POSTGRES_PASS: *db_pass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: FreshRSS
