---
# yaml-language-server: $schema=https://kubernetes-schemas.devbu.io/helmrelease_v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: &app freshrss
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 2.3.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        annotations:
          secret.reloader.stakater.com/auto: "true"
        initContainers:
          init-db:
            order: 1
            image:
              repository: ghcr.io/onedr0p/postgres-init
              tag: 14
              pullPolicy: IfNotPresent
            envFrom: &envFrom
              - secretRef:
                  name: freshrss-secret
        containers:
          main:
            image:
              repository: freshrss/freshrss
              tag: 1.22.1
            env:
              TZ: Europe/Berlin
              CRON_MIN: "18,48"
            envFrom:
              - secretRef:
                  name: freshrss-secret
            resources:
              requests:
                cpu: 50m
                memory: 256Mi

    service:
      main:
        ports:
          http:
            port: 80

    persistence:
      data:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: freshrss
        globalMounts:
          - path: /var/www/FreshRSS/data
      extensions:
        enable: true
        type: persistentVolumeClaim
        existingClaim: freshrss-extensions
        globalMounts:
          - path: /var/www/FreshRSS/extensions

    ingress:
      main:
        enabled: true
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
          hajimari.io/icon: mdi:rss
        hosts:
          - host: &host "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
