---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: freshrss-config
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-hostpath
  resources:
    requests:
      storage: 1Gi
