---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: unifi
  namespace: flux-system
spec:
  targetNamespace: kube-system
  interval: 10m
  path: "./kubernetes/apps/kube-system/unifi/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
