---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name piped-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        DB_USERNAME: &dbUser "{{ .POSTGRES_USER }}"
        DB_PASSWORD: &dbPass "{{ .POSTGRES_PASS }}"
        # InitDB
        INIT_POSTGRES_HOST: postgres-rw.database.svc.cluster.local
        INIT_POSTGRES_DBNAME: piped
        INIT_POSTGRES_USER: *dbUser
        INIT_POSTGRES_PASS: *dbPass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
        # App
  dataFrom:
    - extract:
        key: piped
    - extract:
        key: cloudnative-pg
