---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: qbittorrent
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qbittorrent-secret
    creationPolicy: Owner
  data:
    - secretKey: WIREGUARD_PRIVATE_KEY
      remoteRef:
        key: Mullvad
        property: WIREGUARD_PRIVATE_KEY
    - secretKey: WIREGUARD_ADDRESSES
      remoteRef:
        key: Mullvad
        property: WIREGUARD_ADDRESSES
    - secretKey: SERVER_HOSTNAMES
      remoteRef:
        key: Mullvad
        property: SERVER_HOSTNAMES
    - secretKey: SERVER_CITIES
      remoteRef:
        key: Mullvad
        property: SERVER_CITIES
