---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          # configmap.reloader.stakater.com/reload: qbittorrent-dnsdist
          secret.reloader.stakater.com/reload: qbittorrent-secret

        pod:
          securityContext:
            fsGroup: 568
            fsGroupChangePolicy: "OnRootMismatch"

        containers:
          main:
            nameOverride: qbittorrent
            image:
              repository: ghcr.io/onedr0p/qbittorrent
              tag: 4.6.7@sha256:5391f94b321d563c3b44136a5e799b7e4e4888926c1c31d3081a1cf3e74a9aec
            env:
              UMASK: "022"
              QBITTORRENT__PORT: &port 8080
            probes:
              liveness:
                enabled: true
              readiness:
                enabled: true
              startup:
                enabled: true
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL

          # dnsdist:
          #   image:
          #     repository: docker.io/powerdns/dnsdist-18
          #     tag: 1.8.3

          gluetun:
            image:
              repository: ghcr.io/qdm12/gluetun
              tag: latest@sha256:1549c2f16645585ac107c906673ef22c1f491c36829a92f34f134083b83ff147
            env:
              - name: VPN_SERVICE_PROVIDER
                value: mullvad
              - name: VPN_TYPE
                value: wireguard
              - name: VPN_INTERFACE
                value: wg0
              - name: FIREWALL
                value: "off"
              - name: DOT
                value: "off"
              - name: FIREWALL_INPUT_PORTS
                value: 8080
                # Allow access to k8s subnets
              - name: FIREWALL_OUTBOUND_SUBNETS
                value: "10.42.0.0/16,10.43.0.0/16"
              - name: DOT
                value: "off"
              # - name: DNS_ADDRESS
              #   value: "127.0.0.2"
            envFrom:
              - secretRef:
                  name: qbittorrent-secret
            securityContext:
              capabilities:
                add:
                  - NET_ADMIN
              allowPrivilegeEscalation: false

          port-forward:
            image:
              repository: ghcr.io/bjw-s/gluetun-qb-port-sync
              tag: v0.0.2@sha256:cb7d25d1a1249d326b9f1cf3afc1c6916b173e6784537245b07044420fd97372
            env:
              GLUETUN_CONTROL_SERVER_HOST: localhost
              GLUETUN_CONTROL_SERVER_PORT: 8000
              QBITTORRENT_HOST: localhost
              QBITTORRENT_WEBUI_PORT: *port
              CRON_ENABLED: true
              CRON_SCHEDULE: "*/5 * * * *"
              LOG_TIMESTAMP: false
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              runAsNonRoot: true
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities:
                drop:
                  - ALL
    service:
      main:
        ports:
          http:
            port: *port

    ingress:
      main:
        enabled: true
        className: "internal"
        hosts:
          - host: &hostname qb.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *hostname

    persistence:
      config:
        enabled: true
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          main:
            main:
              - path: /config
      media:
        type: nfs
        server: 192.168.30.4
        path: /mnt/HDD/media
        advancedMounts:
          main:
            main:
              - path: /data/nas-media

      empty-config:
        type: emptyDir
        advancedMounts:
          main:
            port-forward:
              - path: /config

      # dnsdist-config:
      #   type: configMap
      #   name: qbittorrent-dnsdist
      #   advancedMounts:
      #     main:
      #       dnsdist:
      #         - path: /etc/dnsdist/dnsdist.conf
      #           subPath: dnsdist.conf
      #           readOnly: true
      # gluetun-data:
      #   type: emptyDir
      #   advancedMounts:
      #     main:
      #       gluetun:
      #         - path: /tmp/gluetun
      #       port-forward:
      #         - path: /tmp/gluetun
      #           readOnly: true
