---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: minecraft
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: minecraft
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        RCON_PASSWORD: "{{ .RCON_PASSWORD }}"
        WHITELIST: "{{ .WHITELIST }}"
        OPS: "{{ .OPS }}"
  dataFrom:
    - extract:
        key: Minecraft
