---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta1.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app minecraft
spec:
  interval: 30m
  chart:
    spec:
      # renovate: registryUrl=https://itzg.github.io/minecraft-server-charts/
      chart: minecraft
      version: 4.20.0
      sourceRef:
        kind: HelmRepository
        name: minecraft-server
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  dependsOn:
    - name: democratic-csi-local-path
      namespace: kube-system
  values:
    deploymentAnnotations:
      secret.reloader.stakater.com/reload: &secret minecraft
    image:
      repository: ghcr.io/itzg/minecraft-server
      tag: java17
    resources:
      requests:
        cpu: 500m
      limits:
        memory: 8Gi
    securityContext:
      runAsUser: &uid 568
      fsGroup: *uid
    livenessProbe:
      enabled: false
    readinessProbe:
      enabled: false
    startupProbe:
      enabled: false
    extraEnv:
      TZ: "${TIMEZONE}"
      ENABLE_AUTOPAUSE: FALSE
    persistence:
      dataDir:
        enabled: true
        existingClaim: *app
    serviceAnnotations:
      io.cilium/lb-ipam-ips: "${SVC_MINECRAFT_ADDR}"
    minecraftServer:
      eula: true
      version: 1.20.2
      type: SPIGOT
      forceReDownload: true
      jvmXXOpts: "-XX:MaxRAMPercentage=75"
      memory: 8192M
      difficulty: normal
      spawnProtection: 0
      maxTickTime: -1
      gameMode: creative
      pvp: false
      onlineMode: false
      worldSaveName: Vibecraft
      viewDistance: 12
      spigetResources:
        - 36618 #Prom Exporter
      rcon:
        enabled: true
        serviceType: ClusterIP
      serviceType: LoadBalancer
      extraPorts:
        - name: metrics
          containerPort: 9225
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 9225
          ingress:
            enabled: false
        - name: map
          containerPort: 8123
          protocol: TCP
          service:
            enabled: true
            embedded: false
            type: ClusterIP
            port: 8123
          ingress:
            ingressClassName: internal
            enabled: true
            hosts:
              - name: &host "minecraft.${SECRET_DOMAIN}"
                path: /
            tls:
              - secretName: *host
                hosts:
                  - *host
  valuesFrom:
    - kind: Secret
      name: *secret
      valuesKey: WHITELIST
      targetPath: minecraftServer.whitelist
    - kind: Secret
      name: *secret
      valuesKey: OPS
      targetPath: minecraftServer.ops
    - kind: Secret
      name: *secret
      valuesKey: RCON_PASSWORD
      targetPath: minecraftServer.rcon.password
