---
# yaml-language-server: $schema=https://raw.githubusercontent.com/ishioni/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name n8n-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # N8N
        N8N_ENCRYPTION_KEY: "{{ .N8N_ENCRYPTION_KEY }}"
        DB_POSTGRESDB_HOST: &dbhost postgres16-rw.database.svc.cluster.local
        DB_POSTGRESDB_PORT: "5432"
        DB_POSTGRESDB_DATABASE: &dbname n8n
        DB_POSTGRESDB_USER: &dbuser "{{ .POSTGRES_USER }}"
        DB_POSTGRESDB_PASSWORD: &dbpass "{{ .POSTGRES_PASS }}"
        N8N_SMTP_HOST: "smtp.fastmail.com"
        N8N_SMTP_PORT: "587"
        N8N_SMTP_USER: "{{ .fastmail_username }}"
        N8N_SMTP_PASS: "{{ .fastmail_password }}"
        N8N_SMTP_SENDER: "{{ .EMAIL_SENDER }}"
        # Postgres Init
        INIT_POSTGRES_DBNAME: *dbname
        INIT_POSTGRES_HOST: *dbhost
        INIT_POSTGRES_USER: *dbuser
        INIT_POSTGRES_PASS: *dbpass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: n8n
    - extract:
        key: cloudnative-pg
    - extract:
        key: Fastmail SMTP
      rewrite:
        - regexp:
            source: "(.*)"
            target: "fastmail_$1"
