ansible_become_pass: ENC[AES256_GCM,data:+QsJDpL1XYzDKQ==,iv:DZV62MpP+pUWn7L2To5bEObGwS+4sqinDOc/Auend2k=,tag:pOm1VkoLO2kBDdiZ9zk66Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age167cgxdrk98cq6tzw7eg4rfc4rmr02yqnuavawhhre7pdurgx2czq3xeh56
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNVU9vTzNVTUtUdkhWZER0
            Tkx1Uk9RMm9YL0V0MHNvRUVrNDRIMGpyakRJCjlQSnUyR3VOanFhbUdmQVJ1ZFZ5
            cXRTZFdlbGRoR0xpZm42MlVWQmJTNmMKLS0tIFpHc0YvNXl2YjZRLzdvbE9OcW5E
            VHB5ak92dklrRnV0YThhc3hGaGQvWFUKHvZMXQhzDhtSwCqy7Jek83JGVu0LTAsU
            DNcRpKnqs1z19SDsw6mNdILQTz5FRKAwWGvVxEdmVv6XC3nMg9w5cg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-07T10:16:13Z"
    mac: ENC[AES256_GCM,data:eF2avDGgu7cnEihZaBwUgfG78xTqCqxB2hC+ei+G/Lwx/rIaQ2OGkC41hlaLnOIqMOxjkjZ253dfq3JlUomOVHPHrJkyaVHigxVVKqZYyjKlfNqSGB9XP+0pkFkp/bv4sVRqqJZGwicM+oh4gB9oP5/FLClSEqgD7xGj/FJT6Ak=,iv:evoKb3+XSput+yMWearwzg0PhVC1tGp0m7G3sIL6P8s=,tag:Bmm9O7zDqpC6K1jfFHxd3A==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.7.3
