---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: adguard
  namespace: flux-system
spec:
  targetNamespace: default
  interval: 10m
  path: "./kubernetes/apps/default/adguard/app"
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  wait: true
