---
# yaml-language-server: $schema=https://kubernetes-schemas.haraldkoch.ca/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: nextcloud
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: nextcloud-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        # App
        nextcloud-username: "{{ .username }}"
        nextcloud-password: "{{ .password }}"
        smtp-username: "{{ .fastmail_username }}"
        smtp-password: "{{ .fastmail_password }}"
        smtp-host: smtp.fastmail.com
        REDIS_PASSWORD: "{{ .REDIS_PASS }}"
        S3_ACCESS_KEY: "{{ .S3_ACCESS_KEY }}"
        S3_SECRET_KEY: "{{ .S3_SECRET_KEY }}"
        OIDC_CLIENT_ID: "{{ .OIDC_CLIENT_ID }}"
        OIDC_CLIENT_PASSWORD: "{{ .OIDC_CLIENT_SECRET }}"

        # Postgres Init
        INIT_POSTGRES_DBNAME: nextcloud
        INIT_POSTGRES_HOST: postgres16-rw.database.svc.cluster.local.
        INIT_POSTGRES_USER: "{{ .POSTGRES_USER }}"
        INIT_POSTGRES_PASS: "{{ .POSTGRES_PASS }}"
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"
  dataFrom:
    - extract:
        key: nextcloud
    - extract:
        key: cloudnative-pg
    - extract:
        key: Fastmail SMTP
      rewrite:
        - regexp:
            source: "(.*)"
            target: "fastmail_$1"
