---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
spec:
  interval: 5m
  chart:
    spec:
      chart: ./kubernetes/charts/external-app-template
      sourceRef:
        kind: GitRepository
        name: home-kubernetes
        namespace: flux-system
  values:
    title: Home Assistant
    hostname: "cloud.${SECRET_DOMAIN}"
    service:
      name: nextcloud
      port: 9000
      targetPort: http
      ip: 192.168.30.4
    ingress:
      className: internal
