---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-truenas-media
provisioner: nfs.csi.k8s.io
parameters:
  server: 192.168.30.4
  share: /mnt/HDD/media
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions: ["hard", "noatime"]
