apiVersion: v1
kind: Secret
metadata:
    name: github-webhook-token-secret
    namespace: flux-system
stringData:
    token: ENC[AES256_GCM,data:Aeo2Re5XD1uwa8lpEDpyS/HbQPTsxsRW,iv:btbCFrTddtxZrx2NwV8UBf8faKHfeGCgJyNQZXpKg34=,tag:o3mIZIfgDKafzQ2SvqwJGg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age167cgxdrk98cq6tzw7eg4rfc4rmr02yqnuavawhhre7pdurgx2czq3xeh56
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaaUxHQjRzNUIrZGw0Y1dv
            NUpVajhHaytva0JwZG0zT1A0SyszQzJlaVZNCkpGKzFXdHZ2di95TStIYjVmd1dU
            TTJIbGROUmhaMW42cEpDUHVCa01zZDgKLS0tIDE4bEppbWMya3pTMUhSTUNxdlFR
            eUIvaUVoWmR2WjByS2M2SHNmY3RKdTgKUPgmmqEECUn8y17byrbgDGEuMzi6gtrR
            W7pqYICJEkLj3ai8pfGNCZ0uSICPIG/0Uo+i7g3YLpBPXkW3oranfw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T10:05:58Z"
    mac: ENC[AES256_GCM,data:eDF2m07/8VpHI6lkFVhnEFBb4VY2AjU+FMCBbrFE7cJFKe1DBEkv/y+wE8wU8Ok7V1KCss61bV18OG0UvPQ0fz8tDFfvw/8jj44faVI410coeSj1EbGpAOxsL+N/Vjs42K9J0lIpsvSrCpb/t3cdBM+D6Fv7e/2BhbZSmraoHRw=,iv:CmofTxeIoDxRDYxitHX1whCTygj5AGIGSe3xGc6W4nU=,tag:cQyqJ0h6JbTQGliHiHsKqg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
