---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "{{ .Release.Name }}-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: {{ .Release.Name | title }}
        group: guarded
        url: "https://{{ .Values.hostname }}"
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        conditions:
          - "len([BODY]) > 0"
          - "[STATUS] < 400"
        alerts:
          - type: pushover
