---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &name stirling-pdf
spec:
  interval: 30m
  maxHistory: 3
  chart:
    spec:
      chart: app-template
      version: 3.5.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  values:
    defaultPodOptions:
      annotations:
        instrumentation.opentelemetry.io/inject-java: "true"
    controllers:
      main:
        strategy: Recreate
        containers:
          main:
            image:
              repository: frooodle/s-pdf
              tag: 0.31.1
            env:
              DOCKER_ENABLE_SECURITY: "false"
            resources:
              requests:
                cpu: 25m
                memory: 128Mi
              limits:
                memory: 256Mi
    service:
      main:
        ports:
          http:
            port: 8080
    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: &host pdf.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
