---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: authentik
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: authentik-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        AUTHENTIK_SECRET_KEY: "{{ .authentik_secret_key }}"
        AUTHENTIK_EMAIL__HOST: "{{ .authentik_email_host }}"
        AUTHENTIK_EMAIL__USERNAME: "{{ .authentik_email_username }}"
        AUTHENTIK_EMAIL__PASSWORD: "{{ .fastmail_password }}"
        AUTHENTIK_EMAIL__FROM: "{{ .authentik_email_from }}"

        AUTHENTIK_POSTGRESQL__HOST: &db_host postgres16-rw.database.svc.cluster.local
        AUTHENTIK_POSTGRESQL__NAME: &db_name authentik
        AUTHENTIK_POSTGRESQL__USER: &db_user "{{ .authentik_postgres_user }}"
        AUTHENTIK_POSTGRESQL__PASSWORD: &db_pass "{{ .authentik_postgres_pass }}"
        
        # Postgres Init
        INIT_POSTGRES_DBNAME: *db_name
        INIT_POSTGRES_HOST: *db_host
        INIT_POSTGRES_USER: *db_user
        INIT_POSTGRES_PASS: *db_pass
        INIT_POSTGRES_SUPER_PASS: "{{ .POSTGRES_SUPER_PASS }}"

  dataFrom:
    - extract:
        key: cloudnative-pg
    - extract:
        key: Authentik
      rewrite:
        - regexp:
            source: "(.*)"
            target: "authentik_$1"
    - extract:
        key: Fastmail SMTP
      rewrite:
        - regexp:
            source: "(.*)"
            target: "fastmail_$1"