---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authentik
spec:
  interval: 30m
  chart:
    spec:
      chart: authentik
      version: 2024.8.3
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  values:
    server:
      metrics:
        serviceMonitor:
          enabled: true

      initContainers:
        - name: 01-init-db
          image: "ghcr.io/onedr0p/postgres-init:16.6"
          imagePullPolicy: "IfNotPresent"
          envFrom: &envFrom
            - secretRef:
                name: authentik-secret
      ingress:
        enabled: true
        ingressClassName: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - &host auth.${SECRET_DOMAIN}
        paths:
          - /
        tls:
          - hosts:
              - *host

    authentik:
      log_level: info
      email:
        port: 587
        use_tls: true
      error_reporting:
        enabled: false
        send_pii: false
      redis:
        host: "authentik-redis.security.svc.cluster.local"
        password: ""

    global:
      deploymentAnnotations:
        secret.reloader.stakater.com/reload: authentik-secret,authentik-redis-secret

      envFrom: *envFrom

    postgresql:
      enabled: false

    prometheus:
      rules:
        enabled: true

    redis:
      enabled: false
