---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: &app uptime-kuma
  namespace: flux-system
spec:
  targetNamespace: monitoring
  dependsOn:
    - name: democratic-csi-local
    - name: volsync
  path: ./kubernetes/apps/monitoring/uptime-kuma/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: home-kubernetes
  interval: 30m
  retryInterval: 1m
  timeout: 3m
  postBuild:
    substitute:
      APP: *app
      VOLSYNC_CAPACITY: 1Gi
