---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./hajimari/ks.yaml
  - ./freshrss/ks.yaml
  - ./rss-bridge/ks.yaml
  - ./changedetection/ks.yaml
  - ./browserless/ks.yaml
  # - ./scrypted/ks.yaml
