---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: collabora
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.5.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: docker.io/collabora/code
              tag: 23.05.7.5.1
              pullPolicy: IfNotPresent
            env:
              extra_params: --o:ssl.termination=true --o:ssl.enable=false
    service:
      main:
        ports:
          http:
            port: 9980
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          nginx.ingress.kubernetes.io/upstream-hash-by: "$arg_WOPISrc"
          #ingress.kubernetes.io/whitelist-source-range: "192.168.2.0/16,10.0.0.0/8"
          nginx.ingress.kubernetes.io/enable-global-auth: "false"
        hosts:
          - host: &host collabora.${SECRET_DOMAIN}
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host

