apiVersion: v1
kind: Secret
metadata:
    name: cluster-user-auth
    namespace: flux-system
stringData:
    password: ENC[AES256_GCM,data:0ECPlCVUoq8Fsnd/t41yc74o5FMTMb0L24OtL9HHLlBOM+y3BCUvVSuvyCyRBapRnfRRIxwvNmd+7y4I,iv:BSXEBESzZtwwm9lexWhY4BCyKBmiXcTF9sUHmI39828=,tag:4owRdevjQNaLYGLQQfKp6g==,type:str]
    username: ENC[AES256_GCM,data:R4fGfSE=,iv:FQ116sHykZX0hwIqpauh9FdAT+uSpbNxTqYuHoMUX9k=,tag:4QmhYGOrU5GIekT5lj+Ycw==,type:str]
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age167cgxdrk98cq6tzw7eg4rfc4rmr02yqnuavawhhre7pdurgx2czq3xeh56
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeitUOW0xTUwxQmtBQXZ5
            aWlUZ0Fob0oraDBjTlExazBVSEFqeU83QVFrCkJ3b0xZOU1BcTZOYnZiRy96Rm1n
            aDdjUDlhRFRiVjRMY1FZTlRtRHRPUWcKLS0tIGZZbFh1WWJRdEVrMWpZa0JLVDJV
            QUVUVFRIZWlKamZoWXBVcGpDZkRBTW8KNIEzoOsegs2BnKcYC6IQZDp0HigRYHso
            8bFPmw13VBAOlHBcx2B9kzzYyfNwjEdLSxbgdJQfOYsnn+UUaDTPXg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T09:37:59Z"
    mac: ENC[AES256_GCM,data:8tmgLAREk9baZ6COvr9FcyeP2s94Lc1Y9Ib4+Izq+25yRVJ5umKbv97sdfAEU6flHc/T2yet8EB+DbVkuij8SI0U03tnJrxpKm0xsOkWI07QaL5LZyB6G6/vFdxiyTi0zOgJcgO59bVSAZAPGj6Oi/PpIEcVejlF/xehNkNNvrI=,iv:DGUkk+YL/hQVWpWOViN4TFzchL1k0nmGzUGNeYJxadE=,tag:EPqLHmBWk6qBR19NFC7eQA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
