---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: adguard
spec:
  interval: 5m
  chart:
    spec:
      chart: ./kubernetes/charts/external-app-template
      sourceRef:
        kind: GitRepository
        name: home-kubernetes
        namespace: flux-system
  values:
    title: Adguard
    hostname: "adguard.${SECRET_DOMAIN}"
    service:
      name: adguard
      port: 3000
      targetPort: http
      ip: 192.168.40.254
    ingress:
      className: internal
