---
apiVersion: v1
kind: Service
metadata:
  name: adguard
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: http
  type: ClusterIP
---
apiVersion: v1
kind: Endpoints
metadata:
  name: adguard
subsets:
  - addresses:
      - ip: 192.168.40.254
    ports:
      - name: http
        port: 3000
        protocol: TCP
