---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: changedetection
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    defaultPodOptions:
      securityContext:
        runAsUser: 568
        runAsGroup: 568
        fsGroup: 568
        fsGroupChangePolicy: OnRootMismatch
    controllers:
      main:
        type: statefulset
        containers:
          main:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: 0.45.12
            env:
              TZ: Europe/Berlin
              PORT: &port 5000
              PUID: 568
              PGID: 568
              USE_X_SETTINGS: 1
              PLAYWRIGHT_DRIVER_URL: ws://localhost:3000/?stealth=1&--disable-web-security=true&--user-data-dir=~/tmp/cache
              BASE_URL: "https://changedetection.${SECRET_DOMAIN}"
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 500Mi
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
          browser:
            image: 
              repository: ghcr.io/browserless/chrome
              tag: latest@sha256:c4c8836c2421fe6a99a6c8484e7bb8970e4a80bcc9e92dc237ef1aa9557ae613
              pullPolicy: Always
            env:
              SCREEN_WIDTH: "1920"
              SCREEN_HEIGHT: "1024"
              SCREEN_DEPTH: "16"
              CONNECTION_TIMEOUT: "300000"
              CONCURRENT: "10"
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:web-sync
        hosts:
          - host: &host "changedetection.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: changedetection
        globalMounts:
          - path: /datastore