---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: changedetection
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    controllers:
      main:
        type: statefulset
        containers:
          main:
            image:
              repository: ghcr.io/dgtlmoon/changedetection.io
              tag: 0.45.22
            env:
              TZ: Europe/Berlin
              PORT: &port 5000
              PUID: 568
              PGID: 568
              USE_X_SETTINGS: 1
              PLAYWRIGHT_DRIVER_URL: ws://localhost:3000/chrome?stealth=1&--disable-web-security=true&--user-data-dir=~/browserless-cache-123
              BASE_URL: "https://changedetection.${SECRET_DOMAIN}"
            resources:
              requests:
                cpu: 10m
                memory: 100Mi
              limits:
                memory: 500Mi
            probes:
              liveness:
                enabled: false
              readiness:
                enabled: false
              startup:
                enabled: false
            securityContext:
              runAsUser: 568
              runAsGroup: 568
              fsGroup: 568
              fsGroupChangePolicy: OnRootMismatch
          browser:
            image: 
              repository: ghcr.io/browserless/chrome
              tag: latest@sha256:a93bf0abbc1aca5a3e91ef2e00fc9149008c5374e46dc56b3294b2deba83c2e4
              pullPolicy: Always
            env:
              - name: SCREEN_WIDTH
                value: "1920"
              - name: SCREEN_HEIGHT
                value: "1024"
              - name: SCREEN_DEPTH
                value: "16"
              - name: ENABLE_DEBUGGER
                value: "false"
              - name: PREBOOT_CHROME
                value: "true"
              - name: CONNECTION_TIMEOUT
                value: "300000"
              - name: MAX_CONCURRENT_SESSIONS
                value: "10"
              - name: CHROME_REFRESH_TIME
                value: "600000"
              - name: DEFAULT_BLOCK_ADS
                value: "true"
              - name: DEFAULT_STEALTH
                value: "true"
    service:
      main:
        ports:
          http:
            port: *port
    ingress:
      main:
        enabled: true
        className: internal
        annotations:
          hajimari.io/icon: mdi:web-sync
        hosts:
          - host: &host "changedetection.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        type: persistentVolumeClaim
        existingClaim: changedetection
        globalMounts:
          - path: /datastore
