---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../../../templates/gatus/guarded
  - ../../../../templates/volsync
  - ./helmrelease.yaml
patchesStrategicMerge:
  - ./patches/browser.yaml