apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets-user
    namespace: flux-system
stringData:
    SECRET_PLACEHOLDER: ENC[AES256_GCM,data:fR9B5NVhl+ABi3B5,iv:Y9l2EskjhIQfa2WEViQVkXd2I/58GFMeVJlBxKCcF0U=,tag:t962k/uP+02KvMI60/E94A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age167cgxdrk98cq6tzw7eg4rfc4rmr02yqnuavawhhre7pdurgx2czq3xeh56
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpWGc4dE83SFU2WDJmdXFD
            aDFzUm1oWUV6RC9JRU9URVNkdFk0TDhyN3prClUxTzdNcGpqWEdFWVNPYWlOazVh
            a3c5ZW5aT1lKNVQwUXU4QVBkdkxTK28KLS0tIEZsR2ZCQndEMVZYbUhQWUZsZjJP
            cmdnL3N3SGtVMDZTQmg3TzNiQkxsSk0KH8m68DL7jIkeM6y9KUsxGAKFxeRCXG8H
            vaLECksU7z++fGD5gcVZzlZ/bU5q4Vamsln3MRpPaKHosQTP0SAkhg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-11-24T09:37:53Z"
    mac: ENC[AES256_GCM,data:g5/ZsHEytTT7qnz7MgAlBvPnVtZWtr59obeJBTIIuxbgxfg1sz9IEFwh4fjI7kocGIUF9lrLZGB9/6zgEUpsLezhXOnN+KT3XkjNZVFRSJSUiqdPYUV+rUxEA7Ev+25O0+3CSppwvw6UWhy1fl1OW2RWgF5OJl7VwtCazWhVmF8=,iv:MvjKOG6DFkdfOTnilIbZfcLvW1sik4DdDhvDJU6Z30E=,tag:ZJrU19yOddhJvnQd6Dx83Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
