---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: paperless
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: paperless-secret
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        PAPERLESS_ADMIN_USER: "{{ .admin_username }}"
        PAPERLESS_ADMIN_PASSWORD: "{{ .admin_password }}"
        PAPERLESS_SECRET_KEY: "{{ .config_secret_key }}"
        PAPERLESS_SOCIALACCOUNT_PROVIDERS: |
          {
            "openid_connect": {
                "APPS": [
                    {
                        "provider_id": "authentik",
                        "name": "Authentik",
                        "client_id": "QzgBTAWohQEtkO5MU6qtSaUMT8MwCfUS2qMFHpVn",
                        "secret": "{{ .oauth_client_secret }}",
                        "settings": {
                            "server_url": "https://auth.${SECRET_DOMAIN}/application/o/paperless/.well-known/openid-configuration"
                        }
                    }
                ]
            }
          }
  dataFrom:
    - extract:
        key: paperless
