---
# yaml-language-server: $schema=https://raw.githubusercontent.com/fluxcd-community/flux2-schemas/main/helmrelease-helm-v2beta2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: paperless
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 2.6.0
      interval: 30m
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system

  values:
    controllers:
      main:
        annotations:
          reloader.stakater.com/auto: "true"

        pod:
          securityContext:
            supplementalGroups:
              - 1013

        containers:
          main:
            image:
              repository: ghcr.io/paperless-ngx/paperless-ngx
              tag: 2.10.0
            env:
              # Configure application
              PAPERLESS_APPS: allauth.socialaccount.providers.openid_connect
              PAPERLESS_SECRET_KEY:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_SECRET_KEY
              PAPERLESS_URL: https://${HOSTNAME}
              PAPERLESS_PORT: "8000"
              PAPERLESS_TIME_ZONE: "Europe/Berlin"
              PAPERLESS_WEBSERVER_WORKERS: "2"
              PAPERLESS_TASK_WORKERS: "2"
              # Configure Remote User auth
              PAPERLESS_ACCOUNT_ALLOW_SIGNUPS: "false"
              PAPERLESS_SOCIALACCOUNT_ALLOW_SIGNUPS: "false"
              PAPERLESS_SOCIALACCOUNT_PROVIDERS:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_SOCIALACCOUNT_PROVIDERS
              # Configure folders
              PAPERLESS_CONSUMPTION_DIR: /data/nas/inbox
              PAPERLESS_DATA_DIR: /data/local/data
              PAPERLESS_MEDIA_ROOT: /data/nas/media
              # Configure folder importer
              PAPERLESS_CONSUMER_POLLING: "60"
              PAPERLESS_CONSUMER_RECURSIVE: "true"
              PAPERLESS_CONSUMER_SUBDIRS_AS_TAGS: "true"
              # Configure OCR
              PAPERLESS_OCR_LANGUAGE: deu+eng
              # Configure redis integration
              PAPERLESS_REDIS: redis://paperless-redis.default.svc.cluster.local:6379
              # Configure user permissions
              USERMAP_UID: "1012"
              USERMAP_GID: "1013"
              # MISC
              PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
              # Configure admin user
              PAPERLESS_ADMIN_USER:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_ADMIN_USER
              PAPERLESS_ADMIN_PASSWORD:
                valueFrom:
                  secretKeyRef:
                    name: paperless-secret
                    key: PAPERLESS_ADMIN_PASSWORD
            resources:
              requests:
                cpu: 25m
                memory: 3Gi
              limits:
                memory: 7Gi

    service:
      main:
        ports:
          http:
            port: 8000

    ingress:
      main:
        enabled: true
        className: internal
        hosts:
          - host: ${HOSTNAME}
            paths:
              - path: /
                service:
                  name: main
                  port: http
        tls:
          - hosts:
              - ${HOSTNAME}

    persistence:
      data:
        enabled: true
        existingClaim: "${VOLSYNC_CLAIM}"
        advancedMounts:
          main:
            main:
              - path: /data/local
      inbox:
        type: nfs
        server: 192.168.30.4
        path: /mnt/HDD/Paperless/inbox
        globalMounts:
          - path: /data/nas/inbox

      media:
        type: nfs
        server: 192.168.30.4
        path: /mnt/HDD/Paperless/media
        globalMounts:
          - path: /data/nas/media
