apiVersion: v1
kind: Secret
metadata:
    name: cloudflared-secret
stringData:
    TUNNEL_ID: ENC[AES256_GCM,data:Xrm2wHHi5vttxbJdm5VffXuCbWoYG6Qf2c3XvAPgw4arzP6t,iv:XNNKRNI92PCqXNBKfKzNFSRYLDfbXLA4asycRttS/Ek=,tag:LcDSHx72eub4CFhHwEZMbg==,type:str]
    credentials.json: ENC[AES256_GCM,data:ujUAFirU+YAbX3uIeS/R5AQBiv3yR6h/yXpTrGitZRmZl1HmN8D1vGsxK92xnjBxFHCJcENcATLtUypLL1crC2z9cb4vF2j5g6rhwEuAgFHNex1PEG6jFmI7/sHBNn3NqZlpsIHhW3V3dDCjLe3lNKsAOniBrOfUiIDLEwtHhh8rs2a8/NAnDQzylya/vYdnpByCtdp6LXdspot+SO5kRszUVsIHf2GbZxGDkCxmKQ==,iv:a08mB/IUS6FqGeQUE1xuWdEeWC7BdHs5s3bXBIyQa30=,tag:1IVzbfpvlSzWHvoFC0yVmQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age167cgxdrk98cq6tzw7eg4rfc4rmr02yqnuavawhhre7pdurgx2czq3xeh56
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOWG9WMlFRNkpYY1VsSUNN
            ZEhWUmtjek9vRGRpTUtubFVUTjA0aGVwMldVClhxU0hkNDlMcnMrMGgwZ1Z1Z29a
            TlBDYmhISVZWZnI5TGlXZ3NFKy8zSlEKLS0tIEZQalhpNnB4YzEzb0Q0cVVsT2Ru
            ZERKbnN0dU9GWTh2dE9tdzRGVGlmbmsKcO2yr9A0Z6+qiXLu8Na7s931rHnnkRMg
            mpcQutso2/gnjEbaddzKDfpAhmwb+uqEaWQocrAxGkL0mILPVyrmxA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-01T21:44:21Z"
    mac: ENC[AES256_GCM,data:WA6eLdBKyUJRWRYmKFqZKzoUaSHW9pMh+RoLo8CQnnU7bliWdhq+BjPPizh3iDj+4FarVC/DGRdFnX6f6vAyD6NAeY44xiUrKJGyNiNIgs+eQKtBDvxAO9uxf8pCniOL7ehppP0BUGFA054gONAmLCbdJxdJhom3XR2EDyoZUh0=,iv:zdiSh8ERydElR/Y3fmfbA8BP2FQ4ElIeXsR3Hv5AN10=,tag:7+HZF2HObXCzVsOwYvleug==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
