---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: &name tailscale-secret
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: *name
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        TS_AUTHKEY: "{{ .TS_AUTHKEY }}"
  dataFrom:
    - extract:
        key: Tailscale
