---
apiVersion: v1
kind: ConfigMap
metadata:
  name: "adguard-dns-gatus-ep"
  labels:
    gatus.io/enabled: "true"
data:
  config.yaml: |
    endpoints:
      - name: "Tailscale Adguard Home DNS"
        group: guarded
        url: 100.85.84.33
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: "www.google.com"
          query-type: A
        conditions:
          - "len([BODY]) > 0"
        alerts:
          - type: pushover
      - name: "Local Adguard Home DNS"
        group: guarded
        url: 192.168.40.254
        interval: 1m
        ui:
          hide-hostname: true
          hide-url: true
        dns:
          query-name: "www.google.com"
          query-type: A
        conditions:
          - "len([BODY]) > 0"
        alerts:
          - type: pushover
