---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./rbac.yaml
  - ./helmrelease.yaml
configMapGenerator:
  - name: gatus-configmap
    files:
      - ./config/config.yaml
    options:
      annotations:
        kustomize.toolkit.fluxcd.io/substitute: disabled
  - name: gatus-gatus-ep
    files:
      - ./config/gatus.yaml
    options:
      labels:
        gatus.io/enabled: "true"
  - name: gatus-grafana-dashboards
    files:
      - ./dashboards/gatus.json
    options:
      labels:
        grafana_dashboard: "1"
generatorOptions:
  disableNameSuffixHash: true
