---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: gatus
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: gatus
    meta.helm.sh/release-namespace: monitoring
secrets:
  - name: gatus
---
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: gatus
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: gatus
    meta.helm.sh/release-namespace: monitoring
    kubernetes.io/service-account.name: gatus
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gatus
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: gatus
    meta.helm.sh/release-namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "watch", "list"]
  - apiGroups: [""] # "" indicates the core API group
    resources: ["secrets"]
    # Create can not be restricted to a resource name.
    verbs: ["create"]
  - apiGroups: [""] # "" indicates the core API group
    resourceNames: ["tailscale-secret"]
    resources: ["secrets"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gatus
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: gatus
    meta.helm.sh/release-namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: gatus
subjects:
  - kind: ServiceAccount
    name: gatus
    namespace: monitoring

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tailscale
subjects:
  - kind: ServiceAccount
    name: gatus
roleRef:
  kind: ClusterRole
  name: tailscale
  apiGroup: rbac.authorization.k8s.io
